### ISSUE TITLE
recipe responsible for writing files

### ISSUE THREAD

**Issue by brentp** [arq5x/ggd#18]
so a recipe should look like:

```yaml
attributes:
    name: hg38_reference
    version: 1
    sha1:
        - efaaea68910ee444b2756062b2ae2b990d5cdb71
        - 8c6e9635f50256e4ecd84bee2bfb1cb27cc8bbd1

recipe:
    full:
        recipe_type: bash
        recipe_cmds:
            - wget -O hg38.decoy.hla.fa ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
            - samtools faidx hg38.decoy.hla.fa
        recipe_outfiles:
            - hg38.decoy.hla.fa
            - hg38.decoy.hla.fa.fai
```

and ggd knows that the output files are `hg38.decoy.hla.fa` and `.fai` by the `recipe_outfiles` section.
This is instead of the current behavior where ggd captures the output of each command and assumes that it is the file.

this makes it more obvious since the user can implement a full recipe in bash and then translate into the yaml section. I believe this is also what @chapmanb has implemented.
